server.port=8080
spring.application.name=application-service

# Supabase PostgreSQL (Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.hxvoumogiicxipwujaue
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=insurance
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# Calculation Service URL
calculation.service.url=http://localhost:8081

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method