version: '3.8'

services:
  application-service:
    build: .
    container_name: application-service
    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres.hxvoumogiicxipwujaue
      CALCULATION_SERVICE_URL: http://calculation-service:8081

    networks:
      - insurance-network

networks:
  insurance-network:
    external: true